# Generated by Django 3.2.6 on 2021-08-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tomeet'),
    ]

    operations = [
        migrations.CreateModel(
            name='goal_for_month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=100)),
                ('month', models.DurationField()),
                ('difficulty', models.CharField(max_length=100)),
                ('reason_for_goal', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='tomeet',
            name='date_of_meeting',
            field=models.DateTimeField(verbose_name='Meet'),
        ),
        migrations.AlterField(
            model_name='tomeet',
            name='phone_number',
            field=models.IntegerField(verbose_name='Number'),
        ),
    ]
