# Generated by Django 3.2.6 on 2021-08-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210819_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal_for_month',
            name='month',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
