# Generated by Django 3.2.6 on 2021-08-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210820_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('done_for_today', models.CharField(max_length=100)),
                ('important', models.BooleanField(default=False)),
                ('comment', models.BooleanField(default=False)),
            ],
        ),
    ]
