# Generated by Django 3.2.6 on 2021-08-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_habits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='comment',
            field=models.CharField(max_length=100),
        ),
    ]
